# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/zhuelly/Project/Developer/January

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/zhuelly/Project/Developer/January

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/zhuelly/Project/Developer/January/CMakeFiles /media/zhuelly/Project/Developer/January//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/zhuelly/Project/Developer/January/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named january

# Build rule for target.
january: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 january
.PHONY : january

# fast build rule for target.
january/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/build
.PHONY : january/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/system/window.o: src/system/window.cpp.o
.PHONY : src/system/window.o

# target to build an object file
src/system/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/src/system/window.cpp.o
.PHONY : src/system/window.cpp.o

src/system/window.i: src/system/window.cpp.i
.PHONY : src/system/window.i

# target to preprocess a source file
src/system/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/src/system/window.cpp.i
.PHONY : src/system/window.cpp.i

src/system/window.s: src/system/window.cpp.s
.PHONY : src/system/window.s

# target to generate assembly for a file
src/system/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/src/system/window.cpp.s
.PHONY : src/system/window.cpp.s

third-party/imgui/backends/imgui_impl_sdl3.o: third-party/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : third-party/imgui/backends/imgui_impl_sdl3.o

# target to build an object file
third-party/imgui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : third-party/imgui/backends/imgui_impl_sdl3.cpp.o

third-party/imgui/backends/imgui_impl_sdl3.i: third-party/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : third-party/imgui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
third-party/imgui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : third-party/imgui/backends/imgui_impl_sdl3.cpp.i

third-party/imgui/backends/imgui_impl_sdl3.s: third-party/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : third-party/imgui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
third-party/imgui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : third-party/imgui/backends/imgui_impl_sdl3.cpp.s

third-party/imgui/backends/imgui_impl_vulkan.o: third-party/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : third-party/imgui/backends/imgui_impl_vulkan.o

# target to build an object file
third-party/imgui/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : third-party/imgui/backends/imgui_impl_vulkan.cpp.o

third-party/imgui/backends/imgui_impl_vulkan.i: third-party/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : third-party/imgui/backends/imgui_impl_vulkan.i

# target to preprocess a source file
third-party/imgui/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : third-party/imgui/backends/imgui_impl_vulkan.cpp.i

third-party/imgui/backends/imgui_impl_vulkan.s: third-party/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : third-party/imgui/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
third-party/imgui/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : third-party/imgui/backends/imgui_impl_vulkan.cpp.s

third-party/imgui/imgui.o: third-party/imgui/imgui.cpp.o
.PHONY : third-party/imgui/imgui.o

# target to build an object file
third-party/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui.cpp.o
.PHONY : third-party/imgui/imgui.cpp.o

third-party/imgui/imgui.i: third-party/imgui/imgui.cpp.i
.PHONY : third-party/imgui/imgui.i

# target to preprocess a source file
third-party/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui.cpp.i
.PHONY : third-party/imgui/imgui.cpp.i

third-party/imgui/imgui.s: third-party/imgui/imgui.cpp.s
.PHONY : third-party/imgui/imgui.s

# target to generate assembly for a file
third-party/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui.cpp.s
.PHONY : third-party/imgui/imgui.cpp.s

third-party/imgui/imgui_demo.o: third-party/imgui/imgui_demo.cpp.o
.PHONY : third-party/imgui/imgui_demo.o

# target to build an object file
third-party/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_demo.cpp.o
.PHONY : third-party/imgui/imgui_demo.cpp.o

third-party/imgui/imgui_demo.i: third-party/imgui/imgui_demo.cpp.i
.PHONY : third-party/imgui/imgui_demo.i

# target to preprocess a source file
third-party/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_demo.cpp.i
.PHONY : third-party/imgui/imgui_demo.cpp.i

third-party/imgui/imgui_demo.s: third-party/imgui/imgui_demo.cpp.s
.PHONY : third-party/imgui/imgui_demo.s

# target to generate assembly for a file
third-party/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_demo.cpp.s
.PHONY : third-party/imgui/imgui_demo.cpp.s

third-party/imgui/imgui_draw.o: third-party/imgui/imgui_draw.cpp.o
.PHONY : third-party/imgui/imgui_draw.o

# target to build an object file
third-party/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_draw.cpp.o
.PHONY : third-party/imgui/imgui_draw.cpp.o

third-party/imgui/imgui_draw.i: third-party/imgui/imgui_draw.cpp.i
.PHONY : third-party/imgui/imgui_draw.i

# target to preprocess a source file
third-party/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_draw.cpp.i
.PHONY : third-party/imgui/imgui_draw.cpp.i

third-party/imgui/imgui_draw.s: third-party/imgui/imgui_draw.cpp.s
.PHONY : third-party/imgui/imgui_draw.s

# target to generate assembly for a file
third-party/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_draw.cpp.s
.PHONY : third-party/imgui/imgui_draw.cpp.s

third-party/imgui/imgui_tables.o: third-party/imgui/imgui_tables.cpp.o
.PHONY : third-party/imgui/imgui_tables.o

# target to build an object file
third-party/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_tables.cpp.o
.PHONY : third-party/imgui/imgui_tables.cpp.o

third-party/imgui/imgui_tables.i: third-party/imgui/imgui_tables.cpp.i
.PHONY : third-party/imgui/imgui_tables.i

# target to preprocess a source file
third-party/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_tables.cpp.i
.PHONY : third-party/imgui/imgui_tables.cpp.i

third-party/imgui/imgui_tables.s: third-party/imgui/imgui_tables.cpp.s
.PHONY : third-party/imgui/imgui_tables.s

# target to generate assembly for a file
third-party/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_tables.cpp.s
.PHONY : third-party/imgui/imgui_tables.cpp.s

third-party/imgui/imgui_widgets.o: third-party/imgui/imgui_widgets.cpp.o
.PHONY : third-party/imgui/imgui_widgets.o

# target to build an object file
third-party/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_widgets.cpp.o
.PHONY : third-party/imgui/imgui_widgets.cpp.o

third-party/imgui/imgui_widgets.i: third-party/imgui/imgui_widgets.cpp.i
.PHONY : third-party/imgui/imgui_widgets.i

# target to preprocess a source file
third-party/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_widgets.cpp.i
.PHONY : third-party/imgui/imgui_widgets.cpp.i

third-party/imgui/imgui_widgets.s: third-party/imgui/imgui_widgets.cpp.s
.PHONY : third-party/imgui/imgui_widgets.s

# target to generate assembly for a file
third-party/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/january.dir/build.make CMakeFiles/january.dir/third-party/imgui/imgui_widgets.cpp.s
.PHONY : third-party/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... january"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/system/window.o"
	@echo "... src/system/window.i"
	@echo "... src/system/window.s"
	@echo "... third-party/imgui/backends/imgui_impl_sdl3.o"
	@echo "... third-party/imgui/backends/imgui_impl_sdl3.i"
	@echo "... third-party/imgui/backends/imgui_impl_sdl3.s"
	@echo "... third-party/imgui/backends/imgui_impl_vulkan.o"
	@echo "... third-party/imgui/backends/imgui_impl_vulkan.i"
	@echo "... third-party/imgui/backends/imgui_impl_vulkan.s"
	@echo "... third-party/imgui/imgui.o"
	@echo "... third-party/imgui/imgui.i"
	@echo "... third-party/imgui/imgui.s"
	@echo "... third-party/imgui/imgui_demo.o"
	@echo "... third-party/imgui/imgui_demo.i"
	@echo "... third-party/imgui/imgui_demo.s"
	@echo "... third-party/imgui/imgui_draw.o"
	@echo "... third-party/imgui/imgui_draw.i"
	@echo "... third-party/imgui/imgui_draw.s"
	@echo "... third-party/imgui/imgui_tables.o"
	@echo "... third-party/imgui/imgui_tables.i"
	@echo "... third-party/imgui/imgui_tables.s"
	@echo "... third-party/imgui/imgui_widgets.o"
	@echo "... third-party/imgui/imgui_widgets.i"
	@echo "... third-party/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

